// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigs() {
  return window['go']['main']['CONFIG']['GetConfigs']();
}

export function InitConfig() {
  return window['go']['main']['CONFIG']['InitConfig']();
}

export function Start(arg1) {
  return window['go']['main']['CONFIG']['Start'](arg1);
}
