// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {common} from '../models';

export function GetConfigs():Promise<Array<main.TypeConfig>>;

export function GetENVConfigs():Promise<common.YamlInfo>;

export function InitConfig():Promise<boolean>;

export function Start(arg1:main.Config):Promise<boolean>;
