// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigs() {
  return window['go']['main']['GOContext']['GetConfigs']();
}

export function GetENVConfigs() {
  return window['go']['main']['GOContext']['GetENVConfigs']();
}

export function GetRefreshTime() {
  return window['go']['main']['GOContext']['GetRefreshTime']();
}

export function GetStartTime() {
  return window['go']['main']['GOContext']['GetStartTime']();
}

export function InitConfig() {
  return window['go']['main']['GOContext']['InitConfig']();
}

export function InitEnv() {
  return window['go']['main']['GOContext']['InitEnv']();
}

export function SaveENVConfigs(arg1) {
  return window['go']['main']['GOContext']['SaveENVConfigs'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['GOContext']['Start'](arg1);
}

export function TestCmdExec(arg1) {
  return window['go']['main']['GOContext']['TestCmdExec'](arg1);
}
